databases:
  - name: my-database
    plan: free
    region: oregon

services:
  - type: web
    name: my-drf-app
    env: python
    plan: free
    buildCommand: "pip install -r myproject/requirements.txt && python myproject/manage.py collectstatic --noinput && python myproject/manage.py migrate"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: my-drf-app.onrender.com
